[command]
name = "decode"
description = "Decrypt data with FRANZEN"
disable_help_flag = true
disable_version_flag = true
disable_help_subcommand = true

[[command.arguments]]
id = "input"
position = 1
value_name = "FILE"
value_hint = "file_path"

[[command.arguments]]
id = "output"
position = 2
value_name = "FILE"
value_hint = "file_path"

[[command.arguments]]
id = "password"
position = 3
value_name = "PASSWORD"
