[command]
name = "sha1sum"
description = "Compare a local folder with a remote folder using SHA-1"
disable_help_flag = true
disable_version_flag = true
disable_help_subcommand = true

[[command.arguments]]
id = "local_path"
position = 1
value_name = "PATH"
value_hint = "any_path"
