[command]
name = "last"
description = "Get the last multipart filename"
disable_help_flag = true
disable_version_flag = true
disable_help_subcommand = true

[[command.arguments]]
id = "pattern"
position = 1
value_name = "PATTERN"
value_hint = "any_path"
