[command]
name = "devart-red"
description = "Output a red ASCII string"
disable_help_flag = true
disable_version_flag = true
disable_help_subcommand = true

[[command.arguments]]
id = "text"
position = 1
value_name = "TEXT"
