[command]
name = "ads"
description = "Manipulate NTFS alternate data streams"
disable_help_flag = true
disable_version_flag = true
disable_help_subcommand = true

[[command.arguments]]
id = "archive"
position = 1
value_name = "ARCHIVE"
multiple = true
value_hint = "any_path"
